export const LOAD_QUIZ_QUESTIONS = 'LOAD_QUIZ_QUESTIONS';
export const LOAD_QUIZ_QUESTIONS_SUCCESS = 'LOAD_QUIZ_QUESTIONS_SUCCESS';
export const LOAD_QUIZ_QUESTIONS_ERROR = 'LOAD_QUIZ_QUESTIONS_ERROR';

export const LOAD_IMAGES = 'LOAD_IMAGES';
export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES_SUCCESS';
export const LOAD_IMAGES_ERROR = 'LOAD_IMAGES_ERROR';
